In [1]:
# Predict which customers has high probabilities to respond to the campaign of buying a loan/credit card
# classification problem

In [2]:
# Business problem - Understand
# Business problem to Statistics problem
# Access Data and Assess the required Data
# Get permissions to DataBases to read the data
# Set up benchmark - accuracy - Classification - accuracy,F1 score - 90% to 95%

In [3]:
# Classification Problem

# Machine Learning view

# Logisticregression
# NaiveBayesclassifier
# KNN Classifier
# DecisionTreeClassifier
# Baggingclassifier
# RandomForestclassifer
# AdaBoostClassifier

In [4]:
# Try the above algorithms with GridSearch
# Model with high accuracy will be selected as the best model

In [189]:
# Install and Import all the packages
### Packages related to general operating system & warnings
import os 
import warnings
import joblib # to save the model as pkl file # dump - saving , load - read the model
warnings.filterwarnings('ignore')

#Packages related to data importing, manipulation, exploratory data analysis, data understanding
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
#import pandas_profiling
import scipy.stats as stats

#Packages related to data visualizaiton
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

#Setting plot sizes and type of plot
plt.rc("font", size=14)
plt.rcParams['axes.grid'] = True
plt.figure(figsize=(6,3))
plt.gray()

from matplotlib.backends.backend_pdf import PdfPages

#Modules related to split the data & gridsearch
from sklearn.model_selection import train_test_split, GridSearchCV

#Module related to calculation of metrics
from sklearn import metrics

#Module related to VIF 
from statsmodels.stats.outliers_influence import variance_inflation_factor

#Modules related to preprocessing (Imputation of missings, standardiszation, new features creation, converting categorical to numerical)
from sklearn.impute import MissingIndicator, SimpleImputer
from sklearn.preprocessing import  PolynomialFeatures, KBinsDiscretizer, FunctionTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer, OrdinalEncoder

#Moudles related to feature selection
from sklearn.feature_selection import RFE, RFECV, SelectKBest, chi2, SelectPercentile, f_classif, mutual_info_classif, f_regression, VarianceThreshold, SelectFromModel, mutual_info_classif, mutual_info_regression, SelectFpr, SelectFdr, SelectFwe


#Modules related to pipe line creation for faster processing
from sklearn.pipeline import Pipeline
from sklearn.pipeline import FeatureUnion


#Dumping model into current directory: joblib.dump(model_xg,"my_model.pkl") 
#Loading model: my_model_loaded=joblib.load("my_model.pkl")

#Modules related key techniques of supervised learning 

import statsmodels.formula.api as smf
import statsmodels.tsa as tsa

from sklearn.linear_model import LogisticRegression, LinearRegression, ElasticNet, Lasso, Ridge
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_graphviz, export_text
from sklearn.ensemble import BaggingClassifier, BaggingRegressor,RandomForestClassifier,RandomForestRegressor, AdaBoostClassifier
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
import joblib

In [6]:
# Read the data

data = pd.read_csv("C:/projects/jun_ml/data/input_data/bank-additional.csv",sep = ";")

In [7]:
data.shape

(4119, 21)

In [8]:
# Check the datatypes and non null count

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4119 non-null   int64
 1   job             4119 non-null   object
 2   marital         4119 non-null   object
 3   education       4119 non-null   object
 4   default         4119 non-null   object
 5   housing         4119 non-null   object
 6   loan            4119 non-null   object
 7   contact         4119 non-null   object
 8   month           4119 non-null   object
 9   day_of_week     4119 non-null   object
 10  duration        4119 non-null   int64
 11  campaign        4119 non-null   int64
 12  pdays           4119 non-null   int64
 13  previous        4119 non-null   int64
 14  poutcome        4119 non-null   object
 15  emp.var.rate    4119 non-null   float64
 16  cons.price.idx  4119 non-null   float64
 17  cons.conf.idx   4119 non-null   float64
 18  euribor3m       4119 non-null   float64
 19  nr.employed     4119 non-null   float64
 20  y               4119 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 675.9+ KB

In [10]:
# Find if there are any duplicate records
data.duplicated().sum()

np.int64(0)

In [11]:
# Categorical columns
# One hot encoding - if not ordered - (0,1) - create new columns- gender_M,gender_F
# Ordinal Encoding - ordered (Ed 10th - 4, 12th - 3, Degree - 2, Masters-1) - One single column

In [12]:
# Classification problem
# Imbalance - Balance - Tuningparameters
# Imbalance Techniques - SMOTE,Undersampling....park them

data.y.value_counts()/data.y.count()

y
no     0.890507
yes    0.109493
Name: count, dtype: float64

In [13]:
# Clean the column names
# Deal with Categorical Data
# Outlier Treatments

In [14]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [15]:
#Renaming the columsns by replacing special characters with underscore
data.columns = [ i.replace('.', '_') for i in data.columns]

In [16]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y'],
      dtype='object')

In [17]:
#Missing value Treatment
data_cat = data[['job', 'marital', 'education', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome', 'y']]
data_num = data[['age', 'campaign', 'previous', 'emp_var_rate','duration', 'cons_conf_idx']]

In [18]:
# Creating Data audit Report
# Use a general function that returns multiple values
def var_summary(x):
    return pd.Series([x.count(), x.isnull().sum(), x.sum(), x.mean(), x.median(),  x.std(), x.var(), x.min(), x.dropna().quantile(0.01), x.dropna().quantile(0.05),x.dropna().quantile(0.10),x.dropna().quantile(0.25),x.dropna().quantile(0.50),x.dropna().quantile(0.75), x.dropna().quantile(0.90),x.dropna().quantile(0.95), x.dropna().quantile(0.99),x.max()], 
                  index=['N', 'NMISS', 'SUM', 'MEAN','MEDIAN', 'STD', 'VAR', 'MIN', 'P1' , 'P5' ,'P10' ,'P25' ,'P50' ,'P75' ,'P90' ,'P95' ,'P99' ,'MAX'])

num_summary=data_num.apply(lambda x: var_summary(x)).T

In [19]:
num_summary

,N,NMISS,SUM,MEAN,MEDIAN,STD,VAR,MIN,P1,P5,P10,P25,P50,P75,P90,P95,P99,MAX
age,4119.0,0.0,165228.0,40.113620,38.0,10.313362,106.365426,18.0,24.0,26.0,28.8,32.0,38.0,47.0,55.0,58.0,68.00,88.0
campaign,4119.0,0.0,10451.0,2.537266,2.0,2.568159,6.595442,1.0,1.0,1.0,1.0,1.0,2.0,3.0,5.0,7.0,13.00,35.0
previous,4119.0,0.0,784.0,0.190337,0.0,0.541788,0.293535,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,3.00,6.0
emp_var_rate,4119.0,0.0,350.0,0.084972,1.1,1.563114,2.443327,-3.4,-3.4,-2.9,-1.8,-1.8,1.1,1.4,1.4,1.4,1.40,1.4
duration,4119.0,0.0,1057710.0,256.788055,181.0,254.703736,64873.993194,0.0,11.0,35.0,60.0,103.0,181.0,317.0,545.2,740.2,1231.66,3643.0
cons_conf_idx,4119.0,0.0,-166815.8,-40.499102,-41.8,4.594578,21.110142,-50.8,-50.0,-47.1,-46.2,-42.7,-41.8,-36.4,-36.1,-33.6,-26.90,-26.9

In [20]:
def cat_summary(x):
    return pd.Series([x.count(), x.isnull().sum(), x.value_counts()], 
                  index=['N', 'NMISS', 'ColumnsNames'])

cat_summary=data_cat.apply(cat_summary)

In [21]:
cat_summary

,job,marital,education,housing,loan,contact,month,day_of_week,poutcome,y
N,4119,4119,4119,4119,4119,4119,4119,4119,4119,4119
NMISS,0,0,0,0,0,0,0,0,0,0
ColumnsNames,job admin. 1012 blue-collar 88...,marital married 2509 single 1153 divo...,education university.degree 1264 high.sch...,housing yes 2175 no 1839 unknow...,loan no 3349 yes 665 unknown ...,contact cellular 2652 telephone 1467 Na...,month may 1378 jul 711 aug 636 jun ...,day_of_week thu 860 mon 855 tue 841 w...,poutcome nonexistent 3523 failure 4...,"y no 3668 yes 451 Name: count, dtype: ..."

In [22]:
def missing_cat(x):
    t = x.value_counts()
    x[x=='unknown'] = t.index[0]
    return x

def missing_num(x):
    x[x==999] = np.nan
    x = x.fillna(x.median())
    return x

def outlier_capping(x):
    x = x.clip(upper = x.quantile(0.99), lower = x.quantile(0.01) )
    return x

In [23]:
data_num=data_num.apply(outlier_capping)

In [24]:
data_cat=data_cat.apply(missing_cat)
data_num=data_num.apply(missing_num)

In [25]:
data_new = pd.concat([data_num, data_cat], axis=1)

In [26]:
data_new.head()

,age,campaign,previous,emp_var_rate,duration,cons_conf_idx,job,marital,education,housing,loan,contact,month,day_of_week,poutcome,y
0,30,2,0,-1.8,487.0,-46.2,blue-collar,married,basic.9y,yes,no,cellular,may,fri,nonexistent,no
1,39,4,0,1.1,346.0,-36.4,services,single,high.school,no,no,telephone,may,fri,nonexistent,no
2,25,1,0,1.4,227.0,-41.8,services,married,high.school,yes,no,telephone,jun,wed,nonexistent,no
3,38,3,0,1.4,17.0,-41.8,services,married,basic.9y,yes,no,telephone,jun,fri,nonexistent,no
4,47,1,0,-0.1,58.0,-42.0,admin.,married,university.degree,yes,no,cellular,nov,mon,nonexistent,no

In [27]:
data_new = pd.get_dummies(data_new, data_cat.columns, drop_first=True)

In [28]:
df = pd.DataFrame({'Gender' :['M', 'F', 'F']})

In [29]:
pd.get_dummies(df['Gender'], drop_first=True)

       M
0   True
1  False
2  False

In [30]:
data_new

,age,campaign,previous,emp_var_rate,duration,cons_conf_idx,job_blue-collar,job_entrepreneur,job_housemaid,job_management,...,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,y_yes
0,30,2,0,-1.8,487.0,-46.2,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,39,4,0,1.1,346.0,-36.4,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,25,1,0,1.4,227.0,-41.8,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
3,38,3,0,1.4,17.0,-41.8,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,47,1,0,-0.1,58.0,-42.0,False,False,False,False,...,True,False,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4114,30,1,0,1.4,53.0,-42.7,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
4115,39,1,0,1.4,219.0,-42.7,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4116,27,2,1,-1.8,64.0,-46.2,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4117,58,1,0,1.4,528.0,-36.1,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4118,34,1,0,-0.1,175.0,-42.0,False,False,False,True,...,True,False,False,False,False,False,True,True,False,False

In [31]:
data_new = data_new.replace({True: 1, False: 0})

In [32]:
data_new.head()

,age,campaign,previous,emp_var_rate,duration,cons_conf_idx,job_blue-collar,job_entrepreneur,job_housemaid,job_management,...,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,y_yes
0,30,2,0,-1.8,487.0,-46.2,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,39,4,0,1.1,346.0,-36.4,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,25,1,0,1.4,227.0,-41.8,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
3,38,3,0,1.4,17.0,-41.8,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,47,1,0,-0.1,58.0,-42.0,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0

In [33]:
x_cols = data_new.columns.difference(['y_yes'])

In [34]:
x_cols

Index(['age', 'campaign', 'cons_conf_idx', 'contact_telephone',
       'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed', 'duration', 'education_basic.6y',
       'education_basic.9y', 'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'emp_var_rate', 'housing_yes', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'loan_yes', 'marital_married', 'marital_single', 'month_aug',
       'month_dec', 'month_jul', 'month_jun', 'month_mar', 'month_may',
       'month_nov', 'month_oct', 'month_sep', 'poutcome_nonexistent',
       'poutcome_success', 'previous'],
      dtype='object')

In [35]:
X_new = data_new[x_cols]

In [36]:
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(X_new.values, i) for i in range(X_new.shape[1])]
vif["features"] = X_new.columns

print(vif)

    VIF Factor                       features
0    23.659231                            age
1     2.388067                       campaign
2    62.453700                  cons_conf_idx
3     4.122484              contact_telephone
4     2.132458                day_of_week_mon
5     2.134171                day_of_week_thu
6     2.115074                day_of_week_tue
7     2.068096                day_of_week_wed
8     2.253588                       duration
9     1.572900             education_basic.6y
10    2.475866             education_basic.9y
11    3.969183          education_high.school
12    1.017166           education_illiterate
13    2.895232  education_professional.course
14    5.748454    education_university.degree
15    2.661462                   emp_var_rate
16    2.286609                    housing_yes
17    2.782853                job_blue-collar
18    1.187135               job_entrepreneur
19    1.210462                  job_housemaid
20    1.372859                 job_management
21    1.466458                    job_retired
22    1.177264              job_self-employed
23    1.550051                   job_services
24    1.165108                    job_student
25    2.044412                 job_technician
26    1.133968                 job_unemployed
27    1.201942                       loan_yes
28    6.577477                marital_married
29    3.997789                 marital_single
30    4.855450                      month_aug
31    1.125202                      month_dec
32    5.367823                      month_jul
33    3.929475                      month_jun
34    1.237224                      month_mar
35    7.369753                      month_may
36    3.015109                      month_nov
37    1.370549                      month_oct
38    1.368624                      month_sep
39   34.557576           poutcome_nonexistent
40    1.474625               poutcome_success
41    6.010689                       previous

In [37]:
vif_features = vif.loc[vif['VIF Factor']<5,'features'].to_list()

In [38]:
len(vif_features)

34

In [39]:
X_new.shape

(4119, 42)

In [40]:
# vif is for mulitcollinearity, among x variables which can be dropped  X variable
# seleckbest - find most important variables with Y -- best X variables
# rfe -find most important x variables with Y -- best X variables

In [41]:
#intersection of vif x variable and selectbest x variable

In [42]:
# RFE
X = data_new[data_new.columns.difference(['y_yes'])]
classifier = RandomForestClassifier()
rfe = RFE(classifier, n_features_to_select=15)
rfe = rfe.fit(X, data_new[['y_yes']] )

In [43]:
rfe.support_

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False, False, False, False,  True,  True,  True, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True])

In [44]:
X.columns

Index(['age', 'campaign', 'cons_conf_idx', 'contact_telephone',
       'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed', 'duration', 'education_basic.6y',
       'education_basic.9y', 'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'emp_var_rate', 'housing_yes', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'loan_yes', 'marital_married', 'marital_single', 'month_aug',
       'month_dec', 'month_jul', 'month_jun', 'month_mar', 'month_may',
       'month_nov', 'month_oct', 'month_sep', 'poutcome_nonexistent',
       'poutcome_success', 'previous'],
      dtype='object')

In [45]:
rfe_cols = X.columns[rfe.support_]

In [46]:
rfe_cols

Index(['age', 'campaign', 'cons_conf_idx', 'day_of_week_mon',
       'day_of_week_thu', 'day_of_week_tue', 'day_of_week_wed', 'duration',
       'education_university.degree', 'emp_var_rate', 'housing_yes',
       'job_technician', 'marital_married', 'poutcome_success', 'previous'],
      dtype='object')

In [47]:
X = data_new[data_new.columns.difference(['y_yes'])]
SKB = SelectKBest(f_classif, k=15).fit(X, data_new[['y_yes']] )

In [48]:
SKB

SelectKBest(k=15)

In [49]:
SKB.get_support()
SKB_cols = list(X.columns[SKB.get_support()])

In [50]:
SKB_cols

['campaign',
 'contact_telephone',
 'duration',
 'education_university.degree',
 'emp_var_rate',
 'job_blue-collar',
 'job_retired',
 'month_dec',
 'month_mar',
 'month_may',
 'month_oct',
 'month_sep',
 'poutcome_nonexistent',
 'poutcome_success',
 'previous']

In [51]:
vif_features

['campaign',
 'contact_telephone',
 'day_of_week_mon',
 'day_of_week_thu',
 'day_of_week_tue',
 'day_of_week_wed',
 'duration',
 'education_basic.6y',
 'education_basic.9y',
 'education_high.school',
 'education_illiterate',
 'education_professional.course',
 'emp_var_rate',
 'housing_yes',
 'job_blue-collar',
 'job_entrepreneur',
 'job_housemaid',
 'job_management',
 'job_retired',
 'job_self-employed',
 'job_services',
 'job_student',
 'job_technician',
 'job_unemployed',
 'loan_yes',
 'marital_single',
 'month_aug',
 'month_dec',
 'month_jun',
 'month_mar',
 'month_nov',
 'month_oct',
 'month_sep',
 'poutcome_success']

In [52]:
vif_features.extend(rfe_cols)

In [53]:
vif_features.extend(SKB_cols)

In [54]:
sel_cols = set(vif_features)

In [55]:
len(sel_cols)

41

In [56]:
sel_cols = list(sel_cols)

In [57]:
sel_cols = [i.replace(".","_") for i in sel_cols]
sel_cols = [i.replace("-","_") for i in sel_cols]

In [58]:
data_new.shape

(4119, 43)

In [59]:
data_new.columns = [i.replace(".","_") for i in data_new.columns]
data_new.columns = [i.replace("-","_") for i in data_new.columns]

In [60]:
sel_cols

['day_of_week_wed',
 'job_unemployed',
 'housing_yes',
 'education_basic_9y',
 'job_blue_collar',
 'job_retired',
 'education_basic_6y',
 'month_sep',
 'poutcome_nonexistent',
 'month_aug',
 'education_university_degree',
 'day_of_week_tue',
 'poutcome_success',
 'month_mar',
 'contact_telephone',
 'campaign',
 'month_oct',
 'education_illiterate',
 'loan_yes',
 'job_housemaid',
 'job_self_employed',
 'day_of_week_thu',
 'marital_single',
 'month_nov',
 'month_jun',
 'cons_conf_idx',
 'job_student',
 'emp_var_rate',
 'education_high_school',
 'education_professional_course',
 'previous',
 'job_technician',
 'job_management',
 'job_entrepreneur',
 'month_dec',
 'marital_married',
 'day_of_week_mon',
 'duration',
 'job_services',
 'month_may',
 'age']

In [61]:
# TrainTestSplit
X_train,X_test, y_train, y_test = train_test_split(data_new[sel_cols],data_new['y_yes'], test_size=0.2, random_state=123)

In [62]:
comb = pd.concat([data_new[sel_cols],data_new['y_yes']], axis = 1)

In [63]:
#for logistic regression using statsmodels
train, test = train_test_split(comb, test_size=0.3, random_state=0)

In [64]:
''.join(i+"+" for i in train.columns.difference(['y_yes']))

'age+campaign+cons_conf_idx+contact_telephone+day_of_week_mon+day_of_week_thu+day_of_week_tue+day_of_week_wed+duration+education_basic_6y+education_basic_9y+education_high_school+education_illiterate+education_professional_course+education_university_degree+emp_var_rate+housing_yes+job_blue_collar+job_entrepreneur+job_housemaid+job_management+job_retired+job_self_employed+job_services+job_student+job_technician+job_unemployed+loan_yes+marital_married+marital_single+month_aug+month_dec+month_jun+month_mar+month_may+month_nov+month_oct+month_sep+poutcome_nonexistent+poutcome_success+previous+'

In [65]:
logreg = smf.logit(formula='y_yes~age+campaign+cons_conf_idx+contact_telephone+day_of_week_mon+day_of_week_thu+day_of_week_tue+day_of_week_wed+duration+education_basic_6y+education_basic_9y+education_high_school+education_illiterate+education_professional_course+education_university_degree+emp_var_rate+housing_yes+job_blue_collar+job_entrepreneur+job_housemaid+job_management+job_retired+job_self_employed+job_services+job_student+job_technician+job_unemployed+loan_yes+marital_single+month_aug+month_dec+month_jun+month_mar+month_may+month_nov+month_oct+month_sep+poutcome_nonexistent+poutcome_success+previous', data=train)
result = logreg.fit()

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.184359
         Iterations: 35

C:\Users\ravul\anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [66]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  y_yes   No. Observations:                 2883
Model:                          Logit   Df Residuals:                     2842
Method:                           MLE   Df Model:                           40
Date:                Sun, 23 Aug 2026   Pseudo R-squ.:                  0.4807
Time:                        14:14:11   Log-Likelihood:                -531.51
converged:                      False   LL-Null:                       -1023.6
Covariance Type:            nonrobust   LLR p-value:                2.390e-180
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                        -4.5149      1.194     -3.783      0.000      -6.854      -2.175
age                               0.0076      0.010      0.733      0.464      -0.013       0.028
campaign                         -0.0722      0.054     -1.338      0.181      -0.178       0.034
cons_conf_idx                     0.0380      0.020      1.885      0.059      -0.002       0.077
contact_telephone                -0.7193      0.291     -2.476      0.013      -1.289      -0.150
day_of_week_mon                   0.3005      0.271      1.110      0.267      -0.230       0.831
day_of_week_thu                   0.3446      0.267      1.291      0.197      -0.179       0.868
day_of_week_tue                   0.2823      0.267      1.057      0.290      -0.241       0.806
day_of_week_wed                   0.4268      0.276      1.546      0.122      -0.114       0.968
duration                          0.0064      0.000     18.165      0.000       0.006       0.007
education_basic_6y                0.2532      0.476      0.532      0.595      -0.679       1.186
education_basic_9y               -0.0625      0.398     -0.157      0.875      -0.842       0.717
education_high_school            -0.0610      0.367     -0.166      0.868      -0.780       0.658
education_illiterate            -29.4322   5.86e+06  -5.02e-06      1.000   -1.15e+07    1.15e+07
education_professional_course     0.0085      0.400      0.021      0.983      -0.776       0.793
education_university_degree       0.2648      0.358      0.739      0.460      -0.437       0.967
emp_var_rate                     -0.5737      0.067     -8.582      0.000      -0.705      -0.443
housing_yes                      -0.1083      0.168     -0.644      0.520      -0.438       0.221
job_blue_collar                  -0.1554      0.327     -0.475      0.635      -0.797       0.486
job_entrepreneur                 -0.2224      0.545     -0.408      0.683      -1.290       0.846
job_housemaid                     0.2967      0.532      0.558      0.577      -0.746       1.340
job_management                   -0.1625      0.342     -0.475      0.635      -0.834       0.509
job_retired                      -0.1232      0.407     -0.302      0.762      -0.922       0.675
job_self_employed                -1.9362      0.700     -2.768      0.006      -3.307      -0.565
job_services                      0.1679      0.352      0.478      0.633      -0.521       0.857
job_student                       0.7500      0.433      1.731      0.083      -0.099       1.599
job_technician                    0.1253      0.266      0.472      0.637      -0.395       0.646
job_unemployed                    0.3215      0.503      0.639      0.523      -0.665       1.308
loan_yes                          0.0892      0.222      0.402      0.687      -0.345       0.524
marital_single                    0.1194      0.217      0.549      0.583      -0.307       0.546
month_aug                         0.0512      0.320      0.160      0.873      -0.576       0.678
month_dec                         0.9092      0.673      1.350      0.177      -0.410       2.229
month_jun                         0.6360      0.316      2.014      0.044       0.017       1.255
month_mar                         2.0706      0.459      4.513      0.000       1.171       2.970
month_may                        -0.7723      0.267     -2.895      0.004      -1.295      -0.249
month_nov                        -0.5506      0.323     -1.706      0.088      -1.183       0.082
month_oct                         0.5630      0.472      1.193      0.233      -0.362       1.488
month_sep                         0.7059      0.469      1.506      0.132      -0.213       1.624
poutcome_nonexistent              0.9944      0.389      2.556      0.011       0.232       1.757
poutcome_success                  2.1208      0.333      6.368      0.000       1.468       2.774
previous                          0.7359      0.240      3.068      0.002       0.266       1.206
=================================================================================================
"""

In [67]:
result.predict(test)

3754    0.007598
45      0.158245
2774    0.082203
1170    0.072731
4042    0.021607
          ...
1728    0.006286
1460    0.136185
1363    0.398945
1898    0.011360
3519    0.883811
Length: 1236, dtype: float64

In [68]:
train['pred_y'] = np.where(result.predict(train)>=0.5, 1,0)
test['pred_y'] = np.where(result.predict(test)>=0.5, 1,0)

In [69]:
print(metrics.classification_report(train['y_yes'], train['pred_y']))

              precision    recall  f1-score   support

           0       0.94      0.97      0.95      2554
           1       0.70      0.49      0.58       329

    accuracy                           0.92      2883
   macro avg       0.82      0.73      0.77      2883
weighted avg       0.91      0.92      0.91      2883

In [70]:
print(metrics.classification_report(test['y_yes'], test['pred_y']))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95      1114
           1       0.52      0.39      0.44       122

    accuracy                           0.90      1236
   macro avg       0.73      0.67      0.70      1236
weighted avg       0.89      0.90      0.90      1236

In [71]:
# Class imbalance is identified, class imbalanace has to be adopted

In [72]:
# KNN

# Machine Learning models - which parameter should be selected as best value
# GridSearchCV, RandomizedSearchCV

In [73]:
std = StandardScaler()

In [74]:
std = std.fit(X_train)

In [75]:
train_X_std = pd.DataFrame(std.transform(X_train), columns = X_train.columns)
test_X_std = pd.DataFrame(std.transform(X_test), columns = X_test.columns)

In [76]:
grid = {'n_neighbors':[2,3,4,5,6,7,8,9,10,11,12,13,15], 'weights':['uniform', 'distance']}

In [77]:
gcv_knn = GridSearchCV(KNeighborsClassifier(), param_grid= grid, cv = 5, verbose= True, n_jobs=-1, scoring='accuracy')

In [78]:
gcv_knn.fit(X_train, y_train)

Fitting 5 folds for each of 26 candidates, totalling 130 fits

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                         15],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy', verbose=True)

In [79]:
gcv_knn.best_score_

np.float64(0.8980273141122913)

In [80]:
gcv_knn.cv_results_

{'mean_fit_time': array([0.0226933 , 0.02008996, 0.01905837, 0.01322107, 0.01720572,
        0.01954188, 0.0183249 , 0.02473025, 0.019765  , 0.01628027,
        0.03307223, 0.03405638, 0.02042828, 0.02247934, 0.01696091,
        0.00851135, 0.0106986 , 0.01663008, 0.01898689, 0.01384563,
        0.01624594, 0.01569848, 0.01376433, 0.01295877, 0.01335936,
        0.01420093]),
 'std_fit_time': array([0.01419615, 0.00637451, 0.00676155, 0.00228572, 0.0033218 ,
        0.00492595, 0.00642245, 0.00486775, 0.00656879, 0.00369834,
        0.00279084, 0.00815265, 0.0067792 , 0.00351754, 0.00221548,
        0.00167483, 0.0033795 , 0.00229297, 0.00640264, 0.00326139,
        0.00231128, 0.00191374, 0.00243267, 0.0029005 , 0.00303162,
        0.00408269]),
 'mean_score_time': array([0.36337738, 0.2277946 , 0.04895654, 0.04251189, 0.05226064,
        0.05232182, 0.07583904, 0.0401022 , 0.05504031, 0.13209729,
        0.11512284, 0.07832117, 0.06066413, 0.04940281, 0.04306488,
        0.03134398, 0.04548135, 0.05375085, 0.06180081, 0.05766211,
        0.05341449, 0.05840106, 0.05386181, 0.05019956, 0.0496222 ,
        0.04741902]),
 'std_score_time': array([0.03176946, 0.14303143, 0.00593586, 0.00442672, 0.00254852,
        0.0045076 , 0.01785578, 0.00504066, 0.01801249, 0.05531786,
        0.00924891, 0.01331385, 0.00399646, 0.01018432, 0.00795017,
        0.0026078 , 0.00462975, 0.00776058, 0.0048334 , 0.0106612 ,
        0.01026796, 0.00323163, 0.00388582, 0.00445621, 0.00894833,
        0.00824359]),
 'param_n_neighbors': masked_array(data=[2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10,
                    11, 11, 12, 12, 13, 13, 15, 15],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'n_neighbors': 2, 'weights': 'uniform'},
  {'n_neighbors': 2, 'weights': 'distance'},
  {'n_neighbors': 3, 'weights': 'uniform'},
  {'n_neighbors': 3, 'weights': 'distance'},
  {'n_neighbors': 4, 'weights': 'uniform'},
  {'n_neighbors': 4, 'weights': 'distance'},
  {'n_neighbors': 5, 'weights': 'uniform'},
  {'n_neighbors': 5, 'weights': 'distance'},
  {'n_neighbors': 6, 'weights': 'uniform'},
  {'n_neighbors': 6, 'weights': 'distance'},
  {'n_neighbors': 7, 'weights': 'uniform'},
  {'n_neighbors': 7, 'weights': 'distance'},
  {'n_neighbors': 8, 'weights': 'uniform'},
  {'n_neighbors': 8, 'weights': 'distance'},
  {'n_neighbors': 9, 'weights': 'uniform'},
  {'n_neighbors': 9, 'weights': 'distance'},
  {'n_neighbors': 10, 'weights': 'uniform'},
  {'n_neighbors': 10, 'weights': 'distance'},
  {'n_neighbors': 11, 'weights': 'uniform'},
  {'n_neighbors': 11, 'weights': 'distance'},
  {'n_neighbors': 12, 'weights': 'uniform'},
  {'n_neighbors': 12, 'weights': 'distance'},
  {'n_neighbors': 13, 'weights': 'uniform'},
  {'n_neighbors': 13, 'weights': 'distance'},
  {'n_neighbors': 15, 'weights': 'uniform'},
  {'n_neighbors': 15, 'weights': 'distance'}],
 'split0_test_score': array([0.8983308 , 0.8801214 , 0.8892261 , 0.8861912 , 0.8952959 ,
        0.892261  , 0.8983308 , 0.8952959 , 0.89984825, 0.8983308 ,
        0.90440061, 0.89984825, 0.90440061, 0.90136571, 0.90288316,
        0.90440061, 0.90591806, 0.90288316, 0.90440061, 0.90591806,
        0.90288316, 0.90591806, 0.90743551, 0.90743551, 0.89984825,
        0.90591806]),
 'split1_test_score': array([0.8983308 , 0.87860395, 0.89377845, 0.892261  , 0.892261  ,
        0.8983308 , 0.8983308 , 0.89681335, 0.89681335, 0.89681335,
        0.89377845, 0.8952959 , 0.8952959 , 0.89984825, 0.8952959 ,
        0.89377845, 0.8952959 , 0.89377845, 0.8952959 , 0.8952959 ,
        0.892261  , 0.89377845, 0.8952959 , 0.892261  , 0.8952959 ,
        0.89681335]),
 'split2_test_score': array([0.88467375, 0.86798179, 0.87860395, 0.87708649, 0.89074355,
        0.87556904, 0.88163885, 0.87556904, 0.8892261 , 0.8861912 ,
        0.89074355, 0.88467375, 0.892261  , 0.89074355, 0.8892261 ,
        0.88770865, 0.89074355, 0.8861912 , 0.89377845, 0.8892261 ,
        0.8892261 , 0.88770865, 0.892261  , 0.892261  , 0.89377845,
        0.8952959 ]),
 'split3_test_score': array([0.88770865, 0.87556904, 0.8831563 , 0.8801214 , 0.892261  ,
        0.88770865, 0.89074355, 0.88770865, 0.89681335, 0.8983308 ,
        0.89074355, 0.8861912 , 0.8952959 , 0.89074355, 0.89681335,
        0.89377845, 0.89681335, 0.89377845, 0.89377845, 0.89377845,
        0.89377845, 0.8952959 , 0.8892261 , 0.892261  , 0.892261  ,
        0.8952959 ]),
 'split4_test_score': array([0.8983308 , 0.87556904, 0.89681335, 0.892261  , 0.90288316,
        0.89377845, 0.90136571, 0.8952959 , 0.90288316, 0.8983308 ,
        0.8952959 , 0.892261  , 0.90288316, 0.8983308 , 0.89681335,
        0.89377845, 0.89681335, 0.8952959 , 0.8983308 , 0.8952959 ,
        0.89984825, 0.8952959 , 0.89681335, 0.89377845, 0.89984825,
        0.89681335]),
 'mean_test_score': array([0.89347496, 0.87556904, 0.88831563, 0.88558422, 0.89468892,
        0.88952959, 0.89408194, 0.89013657, 0.89711684, 0.89559939,
        0.89499241, 0.89165402, 0.89802731, 0.89620637, 0.89620637,
        0.89468892, 0.89711684, 0.89438543, 0.89711684, 0.89590288,
        0.89559939, 0.89559939, 0.89620637, 0.89559939, 0.89620637,
        0.89802731]),
 'std_test_score': array([0.00602411, 0.00418332, 0.00669056, 0.00619001, 0.0043559 ,
        0.00776128, 0.00714331, 0.00794889, 0.00454222, 0.00474067,
        0.00502366, 0.00564524, 0.00474067, 0.00456246, 0.0043559 ,
        0.00539496, 0.00493113, 0.00530891, 0.00400331, 0.00547966,
        0.00502366, 0.00586922, 0.00619001, 0.00594717, 0.00312462,
        0.00400331]),
 'rank_test_score': array([20, 26, 24, 25, 17, 23, 19, 22,  3, 11, 15, 21,  1,  6,  6, 16,  3,
        18,  3, 10, 11, 11,  6, 11,  6,  1], dtype=int32)}

In [81]:
gcv_knn.best_params_

{'n_neighbors': 8, 'weights': 'uniform'}

In [82]:
knn_best = KNeighborsClassifier(n_neighbors=15, weights= 'distance')

In [83]:
knn_best.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=15, weights='distance')

In [84]:
knn_best.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
print(metrics.classification_report(y_train, knn_best.predict(X_train)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2936
           1       1.00      1.00      1.00       359

    accuracy                           1.00      3295
   macro avg       1.00      1.00      1.00      3295
weighted avg       1.00      1.00      1.00      3295

In [86]:
print(metrics.classification_report(y_test, knn_best.predict(X_test)))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94       732
           1       0.62      0.20      0.30        92

    accuracy                           0.90       824
   macro avg       0.76      0.59      0.62       824
weighted avg       0.87      0.90      0.87       824

In [88]:
# Class imbalance

In [89]:
# imblearn package to access class imbalance tech

In [ ]:
# from imblearn.over_sampling import Random_oversampler

In [90]:
X_train.shape

(3295, 41)

In [91]:
y_train.value_counts()

y_yes
0    2936
1     359
Name: count, dtype: int64

In [94]:
2936*0.5

1468.0

In [96]:
359 - 1468

-1109

In [118]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(
    sampling_strategy= 0.5,
    k_neighbors=2,  # because only 2 minority samples
    random_state=42
)

X_sm, y_sm = smote.fit_resample(X_train, y_train)

In [119]:
X_sm.shape

(4404, 41)

In [120]:
y_sm.value_counts()

y_yes
0    2936
1    1468
Name: count, dtype: int64

In [121]:
# Naive Bayes classifier

In [122]:
nb = GaussianNB()

In [123]:
nb.fit(X_sm, y_sm)

GaussianNB()

In [124]:
print(metrics.classification_report(y_sm, nb.predict(X_sm)))

              precision    recall  f1-score   support

           0       0.92      0.89      0.91      2936
           1       0.80      0.84      0.82      1468

    accuracy                           0.88      4404
   macro avg       0.86      0.87      0.86      4404
weighted avg       0.88      0.88      0.88      4404

In [125]:
print(metrics.classification_report(y_test, nb.predict(X_test)))

              precision    recall  f1-score   support

           0       0.94      0.88      0.91       732
           1       0.38      0.58      0.46        92

    accuracy                           0.85       824
   macro avg       0.66      0.73      0.69       824
weighted avg       0.88      0.85      0.86       824

In [126]:
# DecisionTreeClassifier

In [127]:
dc_tree = DecisionTreeClassifier()

In [128]:
X_sm.shape

(4404, 41)

In [129]:
dc_tree.fit(X_sm, y_sm)

DecisionTreeClassifier()

In [ ]:
dc_tree.predict(X_sm)

In [130]:
print(metrics.classification_report(y_sm, dc_tree.predict(X_sm)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2936
           1       1.00      1.00      1.00      1468

    accuracy                           1.00      4404
   macro avg       1.00      1.00      1.00      4404
weighted avg       1.00      1.00      1.00      4404

In [131]:
print(metrics.classification_report(y_test, dc_tree.predict(X_test)))

              precision    recall  f1-score   support

           0       0.93      0.94      0.94       732
           1       0.49      0.46      0.47        92

    accuracy                           0.89       824
   macro avg       0.71      0.70      0.71       824
weighted avg       0.88      0.89      0.89       824

In [132]:
param_grid = {'max_depth': np.arange(3, 11),
             'max_features': np.arange(3,11),
             'max_leaf_nodes': np.arange(3,11)}

In [133]:
gcv_dtree = GridSearchCV(DecisionTreeClassifier(random_state=123), param_grid= param_grid, cv = 5, n_jobs= -1, scoring= 'accuracy', verbose = True)

In [134]:
gcv_dtree.fit(X_sm, y_sm)

Fitting 5 folds for each of 512 candidates, totalling 2560 fits

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=123),
             n_jobs=-1,
             param_grid={'max_depth': array([ 3,  4,  5,  6,  7,  8,  9, 10]),
                         'max_features': array([ 3,  4,  5,  6,  7,  8,  9, 10]),
                         'max_leaf_nodes': array([ 3,  4,  5,  6,  7,  8,  9, 10])},
             scoring='accuracy', verbose=True)

In [135]:
gcv_dtree.best_params_

{'max_depth': np.int64(8),
 'max_features': np.int64(7),
 'max_leaf_nodes': np.int64(10)}

In [136]:
gcv_dtree.best_score_

np.float64(0.833798369621298)

In [137]:
print(metrics.classification_report(y_sm, gcv_dtree.predict(X_sm)))

              precision    recall  f1-score   support

           0       0.93      0.86      0.89      2936
           1       0.75      0.86      0.80      1468

    accuracy                           0.86      4404
   macro avg       0.84      0.86      0.85      4404
weighted avg       0.87      0.86      0.86      4404

In [138]:
print(metrics.classification_report(y_test, gcv_dtree.predict(X_test)))

              precision    recall  f1-score   support

           0       0.96      0.87      0.91       732
           1       0.40      0.68      0.50        92

    accuracy                           0.85       824
   macro avg       0.68      0.78      0.71       824
weighted avg       0.89      0.85      0.86       824

In [139]:
# BaggingClassifier

In [140]:
y_test.shape

(824,)

In [161]:
param_grid = {'n_estimators' :[10,20,5,4]}

In [152]:
bclass = BaggingClassifier()

In [153]:
bclass.fit(X_sm, y_sm)

BaggingClassifier()

In [154]:
bclass.predict(X_sm)

array([1, 0, 0, ..., 1, 1, 1], shape=(4404,))

In [155]:
print(metrics.classification_report(y_sm, bclass.predict(X_sm)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2936
           1       1.00      0.99      0.99      1468

    accuracy                           1.00      4404
   macro avg       1.00      1.00      1.00      4404
weighted avg       1.00      1.00      1.00      4404

In [156]:
print(metrics.classification_report(y_test, bclass.predict(X_test)))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95       732
           1       0.58      0.47      0.52        92

    accuracy                           0.90       824
   macro avg       0.76      0.71      0.73       824
weighted avg       0.90      0.90      0.90       824

In [157]:
BaggingClassifier?

Init signature:
BaggingClassifier(
    estimator=None,
    n_estimators=10,
    *,
    max_samples=None,
    max_features=1.0,
    bootstrap=True,
    bootstrap_features=False,
    oob_score=False,
    warm_start=False,
    n_jobs=None,
    random_state=None,
    verbose=0,
)
Docstring:
A Bagging classifier.

A Bagging classifier is an ensemble meta-estimator that fits base
classifiers each on random subsets of the original dataset and then
aggregate their individual predictions (either by voting or by averaging)
to form a final prediction. Such a meta-estimator can typically be used as
a way to reduce the variance of a black-box estimator (e.g., a decision
tree), by introducing randomization into its construction procedure and
then making an ensemble out of it.

This algorithm encompasses several works from the literature. When random
subsets of the dataset are drawn as random subsets of the samples, then
this algorithm is known as Pasting [1]_. If samples are drawn with
replacement, then the method is known as Bagging [2]_. When random subsets
of the dataset are drawn as random subsets of the features, then the method
is known as Random Subspaces [3]_. Finally, when base estimators are built
on subsets of both samples and features, then the method is known as
Random Patches [4]_.

Read more in the :ref:`User Guide <bagging>`.

.. versionadded:: 0.15

Parameters
----------
estimator : object, default=None
    The base estimator to fit on random subsets of the dataset.
    If None, then the base estimator is a
    :class:`~sklearn.tree.DecisionTreeClassifier`.

    .. versionadded:: 1.2
       `base_estimator` was renamed to `estimator`.

n_estimators : int, default=10
    The number of base estimators in the ensemble.

max_samples : int or float, default=None
    The number of samples to draw from X to train each base estimator (with
    replacement by default, see `bootstrap` for more details).

    - If None, then draw `X.shape[0]` samples irrespective of `sample_weight`.
    - If int, then draw `max_samples` samples.
    - If float, then draw `max_samples * X.shape[0]` unweighted samples or
      `max_samples * sample_weight.sum()` weighted samples.

max_features : int or float, default=1.0
    The number of features to draw from X to train each base estimator (
    without replacement by default, see `bootstrap_features` for more
    details).

    - If int, then draw `max_features` features.
    - If float, then draw `max(1, int(max_features * n_features_in_))` features.

bootstrap : bool, default=True
    Whether samples are drawn with replacement. If False, sampling without
    replacement is performed. If fitting with `sample_weight`, it is
    strongly recommended to choose True, as only drawing with replacement
    will ensure the expected frequency semantics of `sample_weight`.

bootstrap_features : bool, default=False
    Whether features are drawn with replacement.

oob_score : bool, default=False
    Whether to use out-of-bag samples to estimate
    the generalization error. Only available if bootstrap=True.

warm_start : bool, default=False
    When set to True, reuse the solution of the previous call to fit
    and add more estimators to the ensemble, otherwise, just fit
    a whole new ensemble. See :term:`the Glossary <warm_start>`.

    .. versionadded:: 0.17
       *warm_start* constructor parameter.

n_jobs : int, default=None
    The number of jobs to run in parallel for both :meth:`fit` and
    :meth:`predict`. ``None`` means 1 unless in a
    :obj:`joblib.parallel_backend` context. ``-1`` means using all
    processors. See :term:`Glossary <n_jobs>` for more details.

random_state : int, RandomState instance or None, default=None
    Controls the random resampling of the original dataset
    (sample wise and feature wise).
    If the base estimator accepts a `random_state` attribute, a different
    seed is generated for each instance in the ensemble.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

verbose : int, default=0
    Controls the verbosity when fitting and predicting.

Attributes
----------
estimator_ : estimator
    The base estimator from which the ensemble is grown.

    .. versionadded:: 1.2
       `base_estimator_` was renamed to `estimator_`.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

estimators_ : list of estimators
    The collection of fitted base estimators.

estimators_samples_ : list of arrays
    The subset of drawn samples (i.e., the in-bag samples) for each base
    estimator. Each subset is defined by an array of the indices selected.

estimators_features_ : list of arrays
    The subset of drawn features for each base estimator.

classes_ : ndarray of shape (n_classes,)
    The classes labels.

n_classes_ : int or list
    The number of classes.

oob_score_ : float
    Score of the training dataset obtained using an out-of-bag estimate.
    This attribute exists only when ``oob_score`` is True.

oob_decision_function_ : ndarray of shape (n_samples, n_classes)
    Decision function computed with out-of-bag estimate on the training
    set. If n_estimators is small it might be possible that a data point
    was never left out during the bootstrap. In this case,
    `oob_decision_function_` might contain NaN. This attribute exists
    only when ``oob_score`` is True.

See Also
--------
BaggingRegressor : A Bagging regressor.

References
----------

.. [1] L. Breiman, "Pasting small votes for classification in large
       databases and on-line", Machine Learning, 36(1), 85-103, 1999.

.. [2] L. Breiman, "Bagging predictors", Machine Learning, 24(2), 123-140,
       1996.

.. [3] T. Ho, "The random subspace method for constructing decision
       forests", Pattern Analysis and Machine Intelligence, 20(8), 832-844,
       1998.

.. [4] G. Louppe and P. Geurts, "Ensembles on Random Patches", Machine
       Learning and Knowledge Discovery in Databases, 346-361, 2012.

Examples
--------
>>> from sklearn.svm import SVC
>>> from sklearn.ensemble import BaggingClassifier
>>> from sklearn.datasets import make_classification
>>> X, y = make_classification(n_samples=100, n_features=4,
...                            n_informative=2, n_redundant=0,
...                            random_state=0, shuffle=False)
>>> clf = BaggingClassifier(estimator=SVC(),
...                         n_estimators=10, random_state=0).fit(X, y)
>>> clf.predict([[0, 0, 0, 0]])
array([1])
File:           c:\users\ravul\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py
Type:           ABCMeta
Subclasses:     BalancedBaggingClassifier, EasyEnsembleClassifier

In [160]:
param_grid

{'n_estimators': [10, 20, 5, 4],
 'max_leaf_nodes': array([ 3,  4,  5,  6,  7,  8,  9, 10])}

In [162]:
gcv_bc = GridSearchCV(BaggingClassifier(random_state=123), param_grid= param_grid, cv = 5, n_jobs= -1, verbose = True)

In [163]:
gcv_bc.fit(X_sm, y_sm)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(cv=5, estimator=BaggingClassifier(random_state=123), n_jobs=-1,
             param_grid={'n_estimators': [10, 20, 5, 4]}, verbose=True)

In [ ]:
gcv_bc

In [165]:
print(metrics.classification_report(y_sm, gcv_bc.predict(X_sm)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2936
           1       1.00      1.00      1.00      1468

    accuracy                           1.00      4404
   macro avg       1.00      1.00      1.00      4404
weighted avg       1.00      1.00      1.00      4404

In [166]:
print(metrics.classification_report(y_test, gcv_bc.predict(X_test)))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95       732
           1       0.65      0.60      0.62        92

    accuracy                           0.92       824
   macro avg       0.80      0.78      0.79       824
weighted avg       0.92      0.92      0.92       824

In [167]:
# RandomForest

In [168]:
# Default model with default params

In [169]:
rfc = RandomForestClassifier()

In [170]:
rfc.fit(X_sm, y_sm)

RandomForestClassifier()

In [174]:
print(metrics.classification_report(y_sm, rfc.predict(X_sm)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2936
           1       1.00      1.00      1.00      1468

    accuracy                           1.00      4404
   macro avg       1.00      1.00      1.00      4404
weighted avg       1.00      1.00      1.00      4404

In [175]:
print(metrics.classification_report(y_test, rfc.predict(X_test)))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95       732
           1       0.61      0.46      0.52        92

    accuracy                           0.91       824
   macro avg       0.77      0.71      0.73       824
weighted avg       0.90      0.91      0.90       824

In [176]:
param_grid = {'max_depth': np.arange(3, 6),
             'max_features': np.arange(3,7),
             'max_leaf_nodes': np.arange(3,6),
             'n_estimators' : [10,20,30,40,50,60]}

In [182]:
gcv_rf = GridSearchCV(RandomForestClassifier(random_state=123, class_weight='balanced'), param_grid = param_grid,
             cv = 5, scoring = 'accuracy', n_jobs= -1, verbose= True)

In [183]:
gcv_rf.fit(X_sm, y_sm)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=123),
             n_jobs=-1,
             param_grid={'max_depth': array([3, 4, 5]),
                         'max_features': array([3, 4, 5, 6]),
                         'max_leaf_nodes': array([3, 4, 5]),
                         'n_estimators': [10, 20, 30, 40, 50, 60]},
             scoring='accuracy', verbose=True)

In [184]:
gcv_rf.best_params_

{'max_depth': np.int64(4),
 'max_features': np.int64(3),
 'max_leaf_nodes': np.int64(5),
 'n_estimators': 50}

In [185]:
print(metrics.classification_report(y_sm, gcv_rf.predict(X_sm)))

              precision    recall  f1-score   support

           0       0.94      0.87      0.90      2936
           1       0.78      0.88      0.83      1468

    accuracy                           0.88      4404
   macro avg       0.86      0.88      0.87      4404
weighted avg       0.88      0.88      0.88      4404

In [186]:
print(metrics.classification_report(y_test, gcv_rf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.95      0.88      0.91       732
           1       0.39      0.63      0.49        92

    accuracy                           0.85       824
   macro avg       0.67      0.75      0.70       824
weighted avg       0.89      0.85      0.86       824

In [187]:
# AdaBoost Classifier

In [192]:
abc = AdaBoostClassifier()

In [193]:
abc.fit(X_sm, y_sm)

AdaBoostClassifier()

In [ ]:
abc.predict(X_sm)

In [195]:
print(metrics.classification_report(y_sm, abc.predict(X_sm)))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93      2936
           1       0.88      0.83      0.86      1468

    accuracy                           0.91      4404
   macro avg       0.90      0.89      0.89      4404
weighted avg       0.91      0.91      0.91      4404

In [197]:
print(metrics.classification_report(y_test, abc.predict(X_test)))

              precision    recall  f1-score   support

           0       0.94      0.95      0.94       732
           1       0.54      0.51      0.53        92

    accuracy                           0.90       824
   macro avg       0.74      0.73      0.73       824
weighted avg       0.89      0.90      0.90       824

In [200]:
param_grid = {'n_estimators' : [50,60,30,10]}

In [207]:
# GridSearchcv

gcv_abc = GridSearchCV(AdaBoostClassifier(), param_grid = param_grid, scoring= 'accuracy', verbose = True, n_jobs= -1)

In [208]:
gcv_abc.fit(X_sm, y_sm)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'n_estimators': [50, 60, 30, 10]}, scoring='accuracy',
             verbose=True)

In [209]:
print(metrics.classification_report(y_sm, gcv_abc.predict(X_sm)))

              precision    recall  f1-score   support

           0       0.93      0.94      0.93      2936
           1       0.88      0.85      0.86      1468

    accuracy                           0.91      4404
   macro avg       0.90      0.90      0.90      4404
weighted avg       0.91      0.91      0.91      4404

In [210]:
print(metrics.classification_report(y_test, gcv_abc.predict(X_test)))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94       732
           1       0.54      0.57      0.55        92

    accuracy                           0.90       824
   macro avg       0.74      0.75      0.75       824
weighted avg       0.90      0.90      0.90       824

In [ ]:
# Choose the winner model

In [211]:
gcv_bc.best_params_

{'n_estimators': 20}

In [212]:
best_model_bagging = BaggingClassifier(n_estimators= 20, random_state= 123)

In [213]:
best_model_bagging.fit(X_sm, y_sm)

BaggingClassifier(n_estimators=20, random_state=123)

In [215]:
# file format type
import pickle

In [ ]:
# Step:1 Dump the model to local .dump(model_obj, file_path.pkl)

In [216]:
joblib.dump(best_model_bagging, "C:/projects/jun_ml/data/output_data/best_model_bagging.pkl")

['C:/projects/jun_ml/data/output_data/best_model_bagging.pkl']

In [ ]:
# Step:2, Load it with joblib .load(file_path)

In [217]:
# load the model for predictions

In [218]:
best_model = joblib.load("C:/projects/jun_ml/data/output_data/best_model_bagging.pkl")

In [219]:
best_model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [220]:
# End of the End to End Demonstration